sidebar:
  logo:
    title: Trino的树洞
  menu:
    post: "[文章](/)"
    wiki: "[赛博书摊](/cyber-book-market/)"
    about: "[关于](/about/)"
open_graph:
  enable: false
  twitter_id: # for open_graph meta
widgets:
  # Recent update
  recent:
    layout: recent
    rss: /atom.xml # npm i hexo-generator-feed
    limit: 5 # Count of posts
  # TOC (valid only in layout:post/wiki)
  toc:
    layout: toc
    list_number: false
    min_depth: 2
    max_depth: 5
  # welcome
  welcome:
    layout: markdown
    title: 欢迎
    content: |
      欢迎光临小站，这是一个全新的主题，拥有精心设计的样式，保留了 Volantis 的自定义侧边栏，可以写一些公告。
      本站主题还没开发完毕，旧的文章正在逐步迁移至新主题。
# comments:
#   service: twikoo
#   twikoo:
#     envId: twikoo-cemment-3g11ke154fc8685b # vercel函数
style:
  font-family:
    body: '"Noto Serif SC", serif'