sidebar:
  logo:
    title: Trino的树洞
  menu:
    post: "[文章](/)"
    wiki: "[书籍](/cyber-book-market/)"
    about: "[关于](/about/)"
  widgets:
    home: search, welcome, recent # for home
    # 博客索引页
    blog_index: search_blog, recent # for categories/tags/archives
    # 文档索引页
    wiki_index: search_docs, recent # for wiki
    # 其它（404）
    others: search, welcome, recent # for 404 and ...
    #### 手动创建的页面 ####
    # 文章内页
    post: search, toc # for pages using 'layout:post'
    # 文档内页
    wiki: search, toc, related # for pages using 'layout:wiki'
    # 其它 layout:page 的页面
    page: welcome, toc, search # for custom pages using 'layout:page'
open_graph:
  enable: true
  twitter_id: # for open_graph meta

# comments:
#   service: twikoo
#   twikoo:
#     envId: twikoo-cemment-3g11ke154fc8685b # vercel函数
style:
  font-family:
    body: '"Noto Serif SC", serif'